Validate artifact and intermediate file urls

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -25,6 +25,8 @@ workflows:
     - _download_sample_artifacts
     - test
     after_run:
+    - _build_artifact_download_urls
+    - _intermediate_file_download_urls
     - _file_redaction
     - _zero_length_file_upload
     - _test_results_deployment
@@ -305,6 +307,58 @@ workflows:
                 exit 1
             fi
 
+  _build_artifact_download_urls:
+    steps:
+    - path::./:
+        title: Upload Artifact
+        run_if: "true"
+        inputs:
+        - build_url: $BITRISE_BUILD_URL
+        - build_api_token: $BITRISE_BUILD_API_TOKEN
+        - permanent_download_url_map_format: "{{range $index, $element := .}}{{if eq $index 0}}{{$element.URL}}{{end}}{{end}}"
+        - deploy_path: "./ipas/ios-simple-objc.ipa"
+        - debug_mode: "true"
+    - bundle::validate_urls: {}
+    - path::./:
+        title: Upload Artifact and Intermediate File
+        run_if: "true"
+        inputs:
+        - build_url: $BITRISE_BUILD_URL
+        - build_api_token: $BITRISE_BUILD_API_TOKEN
+        - permanent_download_url_map_format: "{{range $index, $element := .}}{{if eq $index 0}}{{$element.URL}}{{end}}{{end}}"
+        - deploy_path: "./ipas/ios-simple-objc.ipa"
+        - pipeline_intermediate_files: "./ipas/ios-simple-objc.ipa:IPA"
+        - debug_mode: "true"
+    - bundle::validate_urls: {}
+
+  _intermediate_file_download_urls:
+    steps:
+    - path::./:
+        title: Upload Intermediate File
+        run_if: "true"
+        inputs:
+        - build_url: $BITRISE_BUILD_URL
+        - build_api_token: $BITRISE_BUILD_API_TOKEN
+        - permanent_download_url_map_format: "{{range $index, $element := .}}{{if eq $index 0}}{{$element.URL}}{{end}}{{end}}"
+        - deploy_path: "./ipas/ios-simple-objc.ipa"
+        - pipeline_intermediate_files: "./ipas/ios-simple-objc.ipa:IPA"
+        - debug_mode: "true"
+    - script:
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            
+            echo "BITRISE_PERMANENT_DOWNLOAD_URL_MAP: BITRISE_PERMANENT_DOWNLOAD_URL_MAP"
+            if [ -z "${BITRISE_PERMANENT_DOWNLOAD_URL_MAP}" ]; then
+                echo "BITRISE_PERMANENT_DOWNLOAD_URL_MAP is empty"
+                exit 1
+            elsif ! curl --head --silent --fail "${BITRISE_PERMANENT_DOWNLOAD_URL_MAP}" > /dev/null; then
+                echo "BITRISE_PERMANENT_DOWNLOAD_URL_MAP is invalid"
+                exit 1
+            fi
+
   generate_readme:
     steps:
     - git::https://github.com/bitrise-steplib/steps-readme-generator.git@main:
@@ -319,3 +373,40 @@ workflows:
             #!/bin/bash
             set -ex
             stepman audit --step-yml ./step.yml
+
+step_bundles:
+  validate_urls:
+    steps:
+    - script:
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            
+            echo "BITRISE_PUBLIC_INSTALL_PAGE_URL: $public_install_page_url"
+            if [ -z "${public_install_page_url}" ]; then
+                echo "BITRISE_PUBLIC_INSTALL_PAGE_URL is empty"
+                exit 1
+            elsif ! curl --head --silent --fail "${public_install_page_url}" > /dev/null; then
+                echo "BITRISE_PUBLIC_INSTALL_PAGE_URL is invalid"
+                exit 1
+            fi
+            
+            echo "BITRISE_PERMANENT_DOWNLOAD_URL_MAP: BITRISE_PERMANENT_DOWNLOAD_URL_MAP"
+            if [ -z "${BITRISE_PERMANENT_DOWNLOAD_URL_MAP}" ]; then
+                echo "BITRISE_PERMANENT_DOWNLOAD_URL_MAP is empty"
+                exit 1
+            elsif ! curl --head --silent --fail "${BITRISE_PERMANENT_DOWNLOAD_URL_MAP}" > /dev/null; then
+                echo "BITRISE_PERMANENT_DOWNLOAD_URL_MAP is invalid"
+                exit 1
+            fi
+            
+            echo "BITRISE_ARTIFACT_DETAILS_PAGE_URL: BITRISE_ARTIFACT_DETAILS_PAGE_URL"
+            if [ -z "${BITRISE_ARTIFACT_DETAILS_PAGE_URL}" ]; then
+                echo "BITRISE_ARTIFACT_DETAILS_PAGE_URL is empty"
+                exit 1
+            elsif ! curl --head --silent --fail "${BITRISE_ARTIFACT_DETAILS_PAGE_URL}" > /dev/null; then
+                echo "BITRISE_ARTIFACT_DETAILS_PAGE_URL is invalid"
+                exit 1
+            fi
