Lint codebase

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -134,7 +134,7 @@ workflows:
         - debug_mode: "true"
     - path::./:
         title: Android Test compressed with custom name from file path
-        run_if: true
+        run_if: "true"
         inputs:
         - build_url: $BITRISE_BUILD_URL
         - build_api_token: $BITRISE_BUILD_API_TOKEN
@@ -148,14 +148,14 @@ workflows:
     - script:
         is_always_run: true
         inputs:
-          - content: |-
-              #!/bin/bash
-              set -ex
-              # Force turn on the parallel uploads
-              envman add --key BITRISE_DEPLOY_UPLOAD_CONCURRENCY --value "10"
+        - content: |-
+            #!/bin/bash
+            set -ex
+            # Force turn on the parallel uploads
+            envman add --key BITRISE_DEPLOY_UPLOAD_CONCURRENCY --value "10"
     - path::./:
         title: Many xml resources test
-        run_if: true
+        run_if: "true"
         inputs:
         - build_url: $BITRISE_BUILD_URL
         - build_api_token: $BITRISE_BUILD_API_TOKEN
@@ -168,35 +168,35 @@ workflows:
     - set-env-var:
         is_always_run: true
         inputs:
-          - destination_keys: PIPELINE_FILE_3
-          - value: "./xcresults/xcresult3-flaky-with-rerun.xcresult"
+        - destination_keys: PIPELINE_FILE_3
+        - value: ./xcresults/xcresult3-flaky-with-rerun.xcresult
     - path::./:
         title: Pipeline intermediate file upload
-        run_if: true
+        run_if: "true"
         inputs:
-          - build_url: $BITRISE_BUILD_URL
-          - build_api_token: $BITRISE_BUILD_API_TOKEN
-          - is_compress: "false"
-          - deploy_path: ./ipas/ios-simple-objc.ipa
-          - pipeline_intermediate_files: |-
-              ./ipas/ios-simple-objc.ipa:PIPELINE_FILE_1
-              ./xcresults/xcresult3-flaky-with-rerun.xcresult:PIPELINE_FILE_2
-              PIPELINE_FILE_3
-          - notify_user_groups: $NOTIFY_USER_GROUPS
-          - notify_email_list: $NOTIFY_EMAIL_LIST
-          - is_enable_public_page: "true"
-          - debug_mode: "true"
+        - build_url: $BITRISE_BUILD_URL
+        - build_api_token: $BITRISE_BUILD_API_TOKEN
+        - is_compress: "false"
+        - deploy_path: ./ipas/ios-simple-objc.ipa
+        - pipeline_intermediate_files: |-
+            ./ipas/ios-simple-objc.ipa:PIPELINE_FILE_1
+            ./xcresults/xcresult3-flaky-with-rerun.xcresult:PIPELINE_FILE_2
+            PIPELINE_FILE_3
+        - notify_user_groups: $NOTIFY_USER_GROUPS
+        - notify_email_list: $NOTIFY_EMAIL_LIST
+        - is_enable_public_page: "true"
+        - debug_mode: "true"
     - path::./:
-        title:  Deploy path points to invalid path
+        title: Deploy path points to invalid path
         inputs:
-          - build_url: $BITRISE_BUILD_URL
-          - build_api_token: $BITRISE_BUILD_API_TOKEN
-          - is_compress: "false"
-          - deploy_path: /tmp/nonexistent
-          - notify_user_groups: $NOTIFY_USER_GROUPS
-          - notify_email_list: $NOTIFY_EMAIL_LIST
-          - is_enable_public_page: "true"
-          - debug_mode: "true"
+        - build_url: $BITRISE_BUILD_URL
+        - build_api_token: $BITRISE_BUILD_API_TOKEN
+        - is_compress: "false"
+        - deploy_path: /tmp/nonexistent
+        - notify_user_groups: $NOTIFY_USER_GROUPS
+        - notify_email_list: $NOTIFY_EMAIL_LIST
+        - is_enable_public_page: "true"
+        - debug_mode: "true"
     - script:
         title: Output (generated by the Step) tests
         inputs:
@@ -265,51 +265,51 @@ workflows:
 
   _file_redaction:
     steps:
-      - script:
-          is_always_run: true
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                # Create empty temporary file
-                temp_file_path=$(mktemp)
-                # Add some content
-                echo "this is not a secret\nthis is a secret\nagain not a secret\n" > $temp_file_path
-                
-                # Export the file and the secret as env vars
-                envman add --key FILE_TO_REDACT --value "${temp_file_path}"
-                envman add --key SUPER_SECRET --value "this is a secret" --sensitive
-      - path::./:
-          title: File redaction test
-          run_if: true
-          inputs:
-            - build_url: $BITRISE_BUILD_URL
-            - build_api_token: $BITRISE_BUILD_API_TOKEN
-            - deploy_path: ""
-            - files_to_redact: $FILE_TO_REDACT
-            - debug_mode: "true"
-      - script:
-          is_always_run: true
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -ex
-                actual_content=$(<$FILE_TO_REDACT)
-                expected_content="this is not a secret\n[REDACTED]\nagain not a secret\n"
-                
-                # Fail if the content of the redacted file does not meat our expected value
-                if [[ "$actual_content" != "$expected_content" ]]; then
-                  echo "$FILE_TO_REDACT was not redacted"
-                  echo "Actual content: "$actual_content""
-                  echo "Expected content: "$expected_content""
-                  exit 1
-                fi
+    - script:
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            # Create empty temporary file
+            temp_file_path=$(mktemp)
+            # Add some content
+            echo "this is not a secret\nthis is a secret\nagain not a secret\n" > $temp_file_path
+
+            # Export the file and the secret as env vars
+            envman add --key FILE_TO_REDACT --value "${temp_file_path}"
+            envman add --key SUPER_SECRET --value "this is a secret" --sensitive
+    - path::./:
+        title: File redaction test
+        run_if: "true"
+        inputs:
+        - build_url: $BITRISE_BUILD_URL
+        - build_api_token: $BITRISE_BUILD_API_TOKEN
+        - deploy_path: ""
+        - files_to_redact: $FILE_TO_REDACT
+        - debug_mode: "true"
+    - script:
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            actual_content=$(<$FILE_TO_REDACT)
+            expected_content="this is not a secret\n[REDACTED]\nagain not a secret\n"
+
+            # Fail if the content of the redacted file does not meat our expected value
+            if [[ "$actual_content" != "$expected_content" ]]; then
+                echo "$FILE_TO_REDACT was not redacted"
+                echo "Actual content: "$actual_content""
+                echo "Expected content: "$expected_content""
+                exit 1
+            fi
 
   generate_readme:
     steps:
-      - git::https://github.com/bitrise-steplib/steps-readme-generator.git@main:
-          inputs:
-            - example_section: docs/examples.md
+    - git::https://github.com/bitrise-steplib/steps-readme-generator.git@main:
+        inputs:
+        - example_section: docs/examples.md
 
   audit-this-step:
     steps:
